import "./globals.css";
import { Roboto } from "next/font/google";
import Link from "next/link";
import { BsTelephoneFill } from "react-icons/bs";
import { FaEnvelope, FaInstagram } from "react-icons/fa";
import { BiLogoFacebook, BiLogoLinkedin } from "react-icons/bi";
import { GiHamburgerMenu } from "react-icons/gi";

const roboto = Roboto({ subsets: ["latin"], weight: '400' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header className="flex flex-col p-3 text-myBlue fill-myBlue justify-between h-[26vh]">
          <div className="flex items-center justify-between">
            <span className="flex items-center gap-1">
              <BsTelephoneFill size={21} />
              <Link href="tel:+447883300288">+44 7883 300288</Link>
            </span>
            <span className="bg-myBlue w-[4px] h-[25px]"></span>
            <span className="flex items-center gap-1">
              <FaEnvelope size={21} />
              <Link href="mailto:info@lucrerealty.com">
                info@lucrerealty.com
              </Link>
            </span>
          </div>

          <div className="flex justify-end gap-4">
            <p className="capitalize">Follow us:</p>
            <BiLogoLinkedin size={23} />
            <FaInstagram size={23} />
            <BiLogoFacebook size={23} />
          </div>

          <GiHamburgerMenu className="self-end fill-myBlue" size={23} />
          <nav className="hidden"></nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
